app:
    name: hello-world
    group: cicd-test
    version_control: npm
build:
    builder: none
    container: nginx
    host:
        bundleId: DUVALHUB_DEV_BUNDLE
        url: docker.dev.philippeduval.ca
deploy:
    platforms:
        dev:
            hostname: hello-world.cicd-test.dev.philippeduval.ca
            host:
                bundleId: DUVALHUB_DEV_BUNDLE
                url: docker.dev.philippeduval.ca
        stage:
            hostname: hello-world.cicd-test.stage.philippeduval.ca
            host:
                bundleId: DUVALHUB_DEV_BUNDLE
                url: docker.dev.philippeduval.ca
        prod:
            hostname: hello-world.cicd-test.prod.philippeduval.ca
            host:
                bundleId: DUVALHUB_PROD_BUNDLE
                url: docker.prod.philippeduval.ca                
docker:
    registry: docker.io
    namespace: duvalhub
    repository: helloworld-app
    credentialId: DUVALHUB_DOCKER_CREDENTIALS
